version: "3"
services:
  test:
    container_name: test
    build: ./backend

    depends_on:
      - postgres

  # TODO: Write frontend and reporter images to this test docker container.
  postgres:
    container_name: postgres
    image: "postgres:15"
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    #   Set a volume for data and initial sql script
    #   Maybe configure init db
    volumes:
      - data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local